### ISSUE TITLE
Teleporting

### ISSUE THREAD

**Issue by jiiquu** [jiiquu/Alone-19#10]
Allow the user to move around the space by pointing at a destination and clicking to teleport there

**Comment by jlmndrgn** [comment]
Added basic teleporting with the left hand controller:
* use the grip button to activate the raycast
* teleport to the location marked by the blue reticle with the grip button

Known issues:
* the position and rotation of the brush stroke is not updated with the teleportation, resulting in lines being drawn on just the original position even if user teleported away from it
* the action is a bit fiddly, needs some fine-tuning

![vlcsnap-2020-11-20-11h28m35s676](https://user-images.githubusercontent.com/74710058/99783805-99da4380-2b23-11eb-8ea6-c062a7d19dc3.png)

**Comment by jlmndrgn** [comment]
The position and rotation of the brush stroke are now updated in relation to the user's location. Teleporting now enabled. Also added snap-turn. Controllers are as follows:
* use the grip button to activate the raycast
* teleport to the location marked by the blue reticle with the grip button
* use the right hand controller joystick to turn 45 degrees.
